/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mingyu_posix_SharedMem */

#ifndef _Included_org_mingyu_posix_SharedMem
#define _Included_org_mingyu_posix_SharedMem
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mingyu_posix_SharedMem_IPC_RMID
#define org_mingyu_posix_SharedMem_IPC_RMID 0L
#undef org_mingyu_posix_SharedMem_IPC_SET
#define org_mingyu_posix_SharedMem_IPC_SET 1L
#undef org_mingyu_posix_SharedMem_IPC_STAT
#define org_mingyu_posix_SharedMem_IPC_STAT 2L
#undef org_mingyu_posix_SharedMem_IPC_PRIVATE
#define org_mingyu_posix_SharedMem_IPC_PRIVATE 0L
#undef org_mingyu_posix_SharedMem_IPC_ALLOC
#define org_mingyu_posix_SharedMem_IPC_ALLOC 32768L
#undef org_mingyu_posix_SharedMem_IPC_CREAT
#define org_mingyu_posix_SharedMem_IPC_CREAT 512L
#undef org_mingyu_posix_SharedMem_IPC_EXCL
#define org_mingyu_posix_SharedMem_IPC_EXCL 1024L
#undef org_mingyu_posix_SharedMem_IPC_NOWAIT
#define org_mingyu_posix_SharedMem_IPC_NOWAIT 2048L
#undef org_mingyu_posix_SharedMem_IPC_CI
#define org_mingyu_posix_SharedMem_IPC_CI 4096L
#undef org_mingyu_posix_SharedMem_IPC_NOCLEAR
#define org_mingyu_posix_SharedMem_IPC_NOCLEAR 8192L
#undef org_mingyu_posix_SharedMem_IPC_PHYS
#define org_mingyu_posix_SharedMem_IPC_PHYS 16384L



JNIEXPORT jlong JNICALL Java_org_mingyu_posix_SharedMem_getLBA
  (JNIEnv *, jclass);
/*
 * Class:     org_mingyu_posix_SharedMem
 * Method:    shmctl
 * Signature: (IILorg/mingyu/posix/SharedMem/shmid_ds;)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SharedMem_shmctl
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_mingyu_posix_SharedMem
 * Method:    shmat
 * Signature: (IJI)J
 */
JNIEXPORT jlong JNICALL Java_org_mingyu_posix_SharedMem_shmat
  (JNIEnv *, jobject, jint, jlong, jint);

/*
 * Class:     org_mingyu_posix_SharedMem
 * Method:    shmdt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SharedMem_shmdt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_mingyu_posix_SharedMem
 * Method:    shmget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SharedMem_shmget
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_mingyu_posix_SharedMem
 * Method:    mapping_bytebuffer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_mingyu_posix_SharedMem_mapping_1bytebuffer
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
