/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mingyu_posix_SemSet */

#ifndef _Included_org_mingyu_posix_SemSet
#define _Included_org_mingyu_posix_SemSet
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mingyu_posix_SemSet_IPC_RMID
#define org_mingyu_posix_SemSet_IPC_RMID 0L
#undef org_mingyu_posix_SemSet_IPC_SET
#define org_mingyu_posix_SemSet_IPC_SET 1L
#undef org_mingyu_posix_SemSet_IPC_STAT
#define org_mingyu_posix_SemSet_IPC_STAT 2L
#undef org_mingyu_posix_SemSet_IPC_PRIVATE
#define org_mingyu_posix_SemSet_IPC_PRIVATE 0L
#undef org_mingyu_posix_SemSet_IPC_ALLOC
#define org_mingyu_posix_SemSet_IPC_ALLOC 32768L
#undef org_mingyu_posix_SemSet_IPC_CREAT
#define org_mingyu_posix_SemSet_IPC_CREAT 512L
#undef org_mingyu_posix_SemSet_IPC_EXCL
#define org_mingyu_posix_SemSet_IPC_EXCL 1024L
#undef org_mingyu_posix_SemSet_IPC_NOWAIT
#define org_mingyu_posix_SemSet_IPC_NOWAIT 2048L
#undef org_mingyu_posix_SemSet_IPC_CI
#define org_mingyu_posix_SemSet_IPC_CI 4096L
#undef org_mingyu_posix_SemSet_IPC_NOCLEAR
#define org_mingyu_posix_SemSet_IPC_NOCLEAR 8192L
#undef org_mingyu_posix_SemSet_IPC_PHYS
#define org_mingyu_posix_SemSet_IPC_PHYS 16384L
#undef org_mingyu_posix_SemSet_GETNCNT
#define org_mingyu_posix_SemSet_GETNCNT 3L
#undef org_mingyu_posix_SemSet_GETPID
#define org_mingyu_posix_SemSet_GETPID 4L
#undef org_mingyu_posix_SemSet_GETVAL
#define org_mingyu_posix_SemSet_GETVAL 5L
#undef org_mingyu_posix_SemSet_GETALL
#define org_mingyu_posix_SemSet_GETALL 6L
#undef org_mingyu_posix_SemSet_GETZCNT
#define org_mingyu_posix_SemSet_GETZCNT 7L
#undef org_mingyu_posix_SemSet_SETVAL
#define org_mingyu_posix_SemSet_SETVAL 8L
#undef org_mingyu_posix_SemSet_SETALL
#define org_mingyu_posix_SemSet_SETALL 9L
/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    semget
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_semget
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    semctlb
 * Signature: (IIILorg/mingyu/posix/SemSet/semid_ds;)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_semctlb
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    semctl
 * Signature: (III[S)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_semctl__III_3S
  (JNIEnv *, jclass, jint, jint, jint, jshortArray);

/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    semctl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_semctl__IIII
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    semop
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_semop
  (JNIEnv *, jclass, jint, jshortArray);

/*
 * Class:     org_mingyu_posix_SemSet
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_SemSet_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
