/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mingyu_posix_SharedMem_shmid_ds */

#ifndef _Included_org_mingyu_posix_SharedMem_shmid_ds
#define _Included_org_mingyu_posix_SharedMem_shmid_ds
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
