/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mingyu_posix_IPC_Perm */

#ifndef _Included_org_mingyu_posix_IPC_Perm
#define _Included_org_mingyu_posix_IPC_Perm
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
