/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mingyu_posix_Errno */

#ifndef _Included_org_mingyu_posix_Errno
#define _Included_org_mingyu_posix_Errno
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mingyu_posix_Errno
 * Method:    getErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_Errno_getErrno
  (JNIEnv *, jclass);

/*
 * Class:     org_mingyu_posix_Errno
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mingyu_posix_Errno_strerror
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mingyu_posix_Errno
 * Method:    errno
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mingyu_posix_Errno_errno
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
